### ISSUE TITLE
I only want the bT download function, but I don’t want to see the picture function, how to turn it off

### ISSUE THREAD

**Issue by lhj5426** [sk2589822/Exhentai-Enhancer#39]
I only want the bT download function, but I don’t want to see the picture function, how to turn it off
![image](https://user-images.githubusercontent.com/30548000/204077853-ca2bb4ff-52dd-4158-b235-4d11a0b86cb5.png)
just want to keep this functionality
![image](https://user-images.githubusercontent.com/30548000/204077924-adeeecc2-9b17-4e80-ac0c-daf35ad90df3.png)

How do I turn off this feature if I don’t need it?
Because it is better to look at pictures
https://github.com/TagoDR/MangaOnlineViewer

So how to turn off the picture viewing function?

**Comment by sk2589822** [comment]
I'll try to add switches to let you disable the functions you don't want on the next version.  
For now, If you don't mind the scroll-by-row function on other pages, you could remove line 1889 ~ 1891 and save it.

![image](https://user-images.githubusercontent.com/25762718/204079044-da1030c1-16dc-4db2-bb2a-d168fd56979a.png)

P.S. MangaOnlineViewer 的 README 有提到:
> May get your IP Banned, use with moderation

他的實作方式是一次讀取全部的圖片，exhentai 是有可能把你 ban 掉的。建議不要太常使用。

**Comment by lhj5426** [comment]
> I'll try to add switches to let you disable the functions you don't want on the next version. For now, If you don't mind the scroll-by-row function on other pages, you could remove line 1889 ~ 1891 and save it.
> 
> ![image](https://user-images.githubusercontent.com/25762718/204079044-da1030c1-16dc-4db2-bb2a-d168fd56979a.png)
> 
> P.S. MangaOnlineViewer 的 README 有提到:
> 
> > May get your IP Banned, use with moderation
> 
> 他的實作方式是一次讀取全部的圖片，exhentai 是有可能把你 ban 掉的。建議不要太常使用。

哦 原来可以用中文沟通的嘛 太好了  谢谢   我去删掉试试看
谢谢你的提醒 应该没事的 我一直再用那个 而且我关了限制 几百张图一起加载都没事用好久了
我都是用那个脚本全部加载完然后保存成mhtml 方便离线阅读
![image](https://user-images.githubusercontent.com/30548000/204080074-f5c3e392-1e1b-4805-893e-839a15ac0504.png)
妥妥的 无须担心

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/204080443-8e87c071-4c25-4e03-bff4-e36c3db2f6b0.png)
![image](https://user-images.githubusercontent.com/30548000/204080447-9651cbe1-78dc-47b7-b4b7-c72f3bbe02da.png)
删除并且保存还是会进MPV这个页面

**Comment by sk2589822** [comment]
哦抱歉，我誤會你的問題了
那刪掉 1880 的 redirectIfSinglePageViewer(); 應該就可以了

**Comment by lhj5426** [comment]
> 哦抱歉，我誤會你的問題了 那刪掉 1880 的 redirectIfSinglePageViewer(); 應該就可以了

哈哈对不起 请允许我用中文重新描述问题
您写的这个脚本用来下载E站的种子文件真的是太方便了
比原本网站每次下载要弹出一个窗口再点下载方便太多了
然后呢。因为E站自身的MPV这个功能看图片并不理想而且也不方便保存成mhtml
所以有其他的脚本替代 但是您的脚本已经全局替代接管了看图这一块
所以想要 保留下载BT种子的功能 并且关闭看图
这是我的问题
用英文描述太麻烦了 哈哈

我去试试删掉这个看看

**Comment by sk2589822** [comment]
的確，最一開始會寫這個 script 真的是因為那個 popup 太煩了。

我會再看一下怎麼加上開關，避免之後更新你又得手動再改一次。

**Comment by lhj5426** [comment]
> 的確，最一開始會寫這個 script 真的是因為那個 popup 太煩了。
> 
> 我會再看一下怎麼加上開關，避免之後更新你又得手動再改一次。

非常感谢

**Comment by sk2589822** [comment]
@lhj5426 剛剛更新 1.4.0，把第一個勾勾勾掉應該就可以了，你再試試看

![image](https://user-images.githubusercontent.com/25762718/204087057-90dd6c83-22bd-429b-867f-5d646f238658.png)

**Comment by lhj5426** [comment]
> @lhj5426 剛剛更新 1.4.0 了，把第一個勾勾勾掉應該就可以了，你再試試看
> 
> ![image](https://user-images.githubusercontent.com/25762718/204087057-90dd6c83-22bd-429b-867f-5d646f238658.png)

好速度 谢谢 这就更新去
