### ISSUE TITLE
Load all images

### ISSUE THREAD

**Issue by wxy97321** [sk2589822/Exhentai-Enhancer#44]
能否考虑为“Load all images sequentially if the number of images is more than 200.”功能增加一个开关？在浏览一些超大型画廊需要浏览评论区的时候会有一些麻烦。

**Comment by sk2589822** [comment]
@wxy97321 更新 1.4.8 了，你試試看吧

**Comment by wxy97321** [comment]
已解决，非常感谢

**Comment by sk2589822** [comment]
OK，也感謝你的提議，沒有想到這種情況
