### ISSUE TITLE
Archive Download

### ISSUE THREAD

**Issue by huasheng666** [sk2589822/Exhentai-Enhancer#45]
提个小建议，e站本身可以设置自动用Archive Download下载原件，但要使用H@H下载还是需要点击3次
能否设置将点击一次”Archive Download“就实现下载用H@H下载Original
或者可以做成当鼠标指向“Archive Download”下载窗口就自动悬浮显示，移走鼠标时自动隐藏
感觉这样可能会比较方便，谢谢~

**Comment by sk2589822** [comment]
嗨，想確認一下為什麼下載 H@H 會需要點到 3 次呢？
已下載 Original 來說：點 `Archive Download` -> 點 `Original`，這樣應該是 2 次才對？

你提到的兩種方式都跟我的使用習慣不太符合，尤其是第一種的改法，會造成無法下載其他解析度的問題。
我認為比較好的方式是新增一個設定頁，讓使用者自己決定點擊的行為。  

其實一直有想說要不要寫個設定頁，只是這個腳本最一開始只是想讓我自己使用起來舒服一點才寫的，  
而做設定頁對我自己的使用體驗並沒有什麼幫助，也就沒有什麼動力去做，  
所以可能要等我哪天心血來潮才會寫，先跟你說聲不好意思。

**Comment by sk2589822** [comment]
@huasheng666  
1.7.0 有新增這個功能了，試試看吧。  
![image](https://user-images.githubusercontent.com/25762718/213866742-883ad16d-4149-41a2-b1c8-e96b6ca782e3.png)

**Comment by huasheng666** [comment]
好用，新春佳节更新，感谢感谢，新春快乐~~

**Comment by sk2589822** [comment]
新年快樂
