### ISSUE TITLE
"Enable infinite scroll in Front page" seems not work

### ISSUE THREAD

**Issue by ASIjacket** [sk2589822/Exhentai-Enhancer#46]

**Comment by sk2589822** [comment]
Could you please provide more information?
Like the url, how did you use it and the console log (Press F12 to show it).

**Comment by ASIjacket** [comment]
I uploaded a video, I hope it helps.

[video](https://vqp5s-my.sharepoint.com/:v:/g/personal/web_storage_ee_vqp5s_onmicrosoft_com/ETmtI6WzvYpEmUrCOLwcJocB_cvBg-VS92JOzMzIiv_HDg?e=6QUgRW)


chrome 108, tampermonkey 4.18.1
only run with proxy extension and tampermonkey, no error in the console log

in e-hentai only work in some time. You can see this in the video
but in exhentai script always not work

**Comment by sk2589822** [comment]
(應該看得懂中文，我用中文好了，英文有點難說明)

嗨，感謝你的影片，幫助很大。

想確認一下你右邊的卷軸 (scrollbar) 是原生的嗎？  
因為目前我設定讀取下一頁的觸發時機是滑動到底部時才讀取，不確定是不是這個影響到。  
你可以幫我按按看 End 鍵有沒有用嗎？

**Comment by ASIjacket** [comment]
1. **未更改前**：滚动条是chrome一个测试的新特征，测试关闭以后并不影响，使用 `end` 也没有变化
2. **更改 `733` 判断代码后**: 就可以正常滚动了，几个页面测试下来也没有问题
3. 另外刚发现有趣的现象，这个问题只在部分屏幕上复现，`y.value` 和 `maxScrollHeight` 在1080p 上会差 `0.4` 就没问题，但是在 2.2k(奇葩分辨率) 上会差 `2.27` 出现 bug，神奇的 js feature

最后 感谢你的回复 : )

**Comment by sk2589822** [comment]
感謝測試，原來那樣寫會有誤差，那我下個版本再改成上面一樣，不要設那麼死好了。

**Comment by sk2589822** [comment]
@ASIjacket 
1.6.1 有調整過了，如果還是有問題再麻煩說一下，感謝。
