### ISSUE TITLE
Add to Favorites enhancement 

### ISSUE THREAD

**Issue by AlexanderHel** [sk2589822/Exhentai-Enhancer#50]
Hi I'm the one requested the enhancement on sf.

Thank you for the update, it's working great, but there is something I hope you can add.

Previous in favorite window I can double click these options to add to my favorite, the script does not do it.

![image](https://user-images.githubusercontent.com/99399435/226173243-0d59a85a-85de-4dc4-882c-64275f780054.png)

**Comment by sk2589822** [comment]
I added a event for it. Should be okay now.
