### ISSUE TITLE
Archive Download enhance

### ISSUE THREAD

**Issue by AlexanderHel** [sk2589822/Exhentai-Enhancer#52]
Hi, first I want to thank you for the awesome script, been using it for awhile and can say that I can't use exhentai without it anymore :D

But there is a problem I hope it can be improve

Here is my Archiver Settings

![image](https://user-images.githubusercontent.com/99399435/229716886-5bdf4a56-c717-4d0f-96c7-5e4b3ead651c.png)

And here is what happened when I click Archive Download

![image](https://user-images.githubusercontent.com/99399435/229716982-5d7ccf44-e516-4415-bfa0-e6c31822a60e.png)

I need to click the button `(Click here if your browser does not continue automatically)` to continue

Wonder if the script can be improve so it will auto continue to the download link
![image](https://user-images.githubusercontent.com/99399435/229717798-8b8e65b4-519b-4dc8-90cf-9f4a505adf9a.png)

**Comment by AlexanderHel** [comment]
Actually I already tried to change setting options before I opened the issue

When I changed it to download Original Resolution directly, nothing happened after I clicked Archive Download

**Comment by sk2589822** [comment]
Did you change the Archiver Settings (the first image you post) to "Manual Select, Manual Start (Default)"?

**Comment by AlexanderHel** [comment]
> Have you changed the Archiver Settings (the first image you post) to "Manual Select, Manual Start (Default)"?

Oh I didn't know that, I changed and it's working perfectly now, thank you very much
