### ISSUE TITLE
White page when clicking a picture

### ISSUE THREAD

**Issue by HnnGue** [sk2589822/Exhentai-Enhancer#53]
When i click a picture I can see the site loading for a fraction of a second and then I get a white page that says "eeenope"

**Comment by sk2589822** [comment]
This script will redirect the page to "Multi-Page Viewer" page (which url likes https://exhentai.org/mpv/xxxxx/ooooo) when it detect you're in a "Single-Page Viewer" (which url likes https://exhentai.org/s/xxxxx/ooooo) by default.

However, if you don't have access to MPV, you will see the "eeenope" like the [doc says](https://ehwiki.org/wiki/Technical_Issues)
![image](https://user-images.githubusercontent.com/25762718/233236226-bac2e313-68c8-4c38-a0c2-6aa3991b7f30.png)  

So if you don't want the redirection, you can disable it from settings panel:
![image](https://user-images.githubusercontent.com/25762718/233236887-8c931450-23a5-483c-b97c-23dfb40c8b55.png)
