### ISSUE TITLE
Infinite scroll automatically scrolls to the bottom of the page

### ISSUE THREAD

**Issue by nikgtasa** [sk2589822/Exhentai-Enhancer#54]
Instead of letting new page load and then continue from where i am, it automatically scrolls to the end of the newly loaded page.

**Comment by sk2589822** [comment]
Hi, have you installed other script?

**Comment by nikgtasa** [comment]
I do have other scripts enabled normally, but i turned them all off to see if the bug would disappear and it stayed.

**Comment by sk2589822** [comment]
I see. Could you please provide more information like:

1. The URL that you encountered this issue
2. Which browser you use
3. Which extension you use (e.g. Tampermonkey, Violentmonkey, ...etc.)
4. Size(width & height) of your browser 
5. Press F12 and trigger the Infinite scroll, then see if any error message in your devtool  
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/25762718/7bb8e861-c07a-4181-a144-10f67eaa2b23)

Recording a video clip with devtool opened would be even better.

Thanks!

**Comment by nikgtasa** [comment]
1. Across the entire site.
2. Waterfox G5.1.3 (64-bit)
3. Tampermonkey
4. 1835x884
5. No errors spotted. 
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/38408810/43ea6280-b306-4f43-8ed8-dbd94cedbdf4)
[Waterfox Atfgrdwqg1.webm](https://github.com/sk2589822/Exhentai-Enhancer/assets/38408810/73edf207-60aa-4093-846d-3f3150bed27a)

**Comment by sk2589822** [comment]
Seems it's expected behavior in Waterfox (maybe Firefox as well) that it will keep the scrollbar at the bottom after the new elements has been insert.
I will try to find other way to avoid this issue.

**Comment by sk2589822** [comment]
I just updated to 1.10.3.

It should be fine if you use mouse to scroll to the bottom now.   
But it will still keep at the bottom if you grab the scrollbar to the bottom directly.

Is it okay for you?

**Comment by nikgtasa** [comment]
Yeah, works fine now. Thanks!
