### ISSUE TITLE
How can I get acess to Settings Panel?

### ISSUE THREAD

**Issue by Zenoch8** [sk2589822/Exhentai-Enhancer#55]
When I click on Archive Download this panel doesn't appear. 
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/135635174/ce6cb56b-a755-4bd1-ab52-a03d9bb73941)

**Comment by sk2589822** [comment]
Click the Tampermonkey icon fisrt, then select Open settings panel.  
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/25762718/0eba047f-9ffe-4719-994f-98010b20c26b)

**Comment by Zenoch8** [comment]
Yeah. It works. Thanks!
