### ISSUE TITLE
遇到一个界面bug

### ISSUE THREAD

**Issue by lhj5426** [sk2589822/Exhentai-Enhancer#57]
就是这个
打开大佬的脚本 页面会变成这样 
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/30548000/b863dd3a-baaa-4bf9-b19b-c8241ddf23dd)
 关闭之后
 
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/30548000/b87aa594-7f95-4289-85a9-da7eb5be69d7)
 就是正常的
 
 一个一个脚本 关闭排查的 最后发现是大佬您的脚本 会导致页面变形的

**Comment by sk2589822** [comment]
應該是昨天調整時沒注意到，我再找時間調整，感謝回報

**Comment by lhj5426** [comment]
> 應該是昨天調整時沒注意到，我再找時間調整。 能提供你的瀏覽器及視窗寬度嗎？感謝

1920 1080 的屏幕分辨率 使用的浏览器是EDGE的115

同时开启了侧边标签

**Comment by sk2589822** [comment]
想請問只開啟我的腳本，其他全部關閉也會有此情況嗎？
因為看起來你用的其他腳本也會去改動網頁的 CSS。

我只開啟我的腳本的話看起來是正常的，(我的 Edge 是 `119.0.2151.44`)
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/25762718/e58de35a-64b2-45b3-817a-a552de1261d7)

**Comment by wxy97321** [comment]
> 想請問如果只開啟我的腳本，其他全部關閉也會有此情況嗎？ 因為看起來你用的其他腳本也會去改動網頁的 CSS（圖片跑版，副標變大）。
> 
> 我測試只開啟我的腳本的話，看起來是正常的 （我的 Edge 是 `119.0.2151.44`）。 ![image](https://user-images.githubusercontent.com/25762718/280468957-e58de35a-64b2-45b3-817a-a552de1261d7.png)

我测试了一下，似乎是和 https://github.com/EhTagTranslation/EhSyringe 这个脚本产生了冲突。

**Comment by sk2589822** [comment]
> 我测试了一下，似乎是和 https://github.com/EhTagTranslation/EhSyringe 这个脚本产生了冲突。

感謝幫忙，已於 `1.11.2` 修正。
