### ISSUE TITLE
"Enable Rating Filter" breaks /uploader/<uploader> pages

### ISSUE THREAD

**Issue by soredake** [sk2589822/Exhentai-Enhancer#59]
What you see on https://e-hentai.org/uploader/WindyNii:
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/5204968/804edfe5-23da-4951-a12c-3128deed3eb7)

What you will see after you enable "Enable Rating Filter" and reload page (you are redirected to https://e-hentai.org/?f_search=WindyNii&advsearch=1&f_srdd=2):
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/5204968/305777b9-8b19-455c-bd6c-1d0627c68d0f)

What happens if you manually set minimum rating without enabling "Enable Rating Filter" and press search (you will be redirected to https://e-hentai.org/?f_search=uploader%3AWindyNii&tag_name_bar=%5B%7B%22key%22%3A%22uploader%3AWindyNii%22%2C%22value%22%3A%22uploader%3AWindyNii%22%2C%22editable%22%3Afalse%7D%5D&advsearch=1&f_srdd=2):
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/5204968/d7cd3bf5-ae5a-4a22-897c-b4a4c5842325)

**Comment by sk2589822** [comment]
Thanks for reporting.

I will try to fix it after next Wednesday.

**Comment by sk2589822** [comment]
Hi @soredake,

Is "Enable Rating Filter" a function of e-hentai itself?  
I have never used it before.  

Also, there are no such function exist in my script.

**Comment by soredake** [comment]
> Is "Enable Rating Filter" a function of e-hentai itself?

It's from your script:
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/5204968/86b32a53-aa2e-4d0b-9859-521586bbde0a)

**Comment by sk2589822** [comment]
No, that's not my script.  
Filtering things is not what my script do.

This is the settings of my script:

![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/25762718/ee7a37f0-6a4a-4377-869b-b400365855bd)
