### ISSUE TITLE
[功能请求] 将画廊的申请重命名也适配

### ISSUE THREAD

**Issue by Hayakee** [sk2589822/Exhentai-Enhancer#60]
每次打开申请重命名的新窗口都是不完全展开的，还得自己手动拉，比较麻烦。
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/167681717/49c9494e-e03e-42bf-baac-6d9c261b1468)
![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/167681717/061db77d-d175-41a7-8053-dae1734e5d97)

**Comment by sk2589822** [comment]
嗨 @Hayakee 

因為我會用到的功能已經做得差不多了，所以這個專案已經很少在修改了，

除非是我會用到的功能，不然應該不會考慮實作喔，不好意思。

**Comment by Hayakee** [comment]
啊，没事没事，目前的三个适配体验非常好了，这个功能基本只有参与社区运行的人才会用到，是我考虑适用范围不周了。
还是感谢老哥的脚本，让我在电脑的阅览体验提升很大😄。

**Comment by sk2589822** [comment]
嗨！ @Hayakee 

突然看到這個 issue。之前沒有看到你困擾的點：

> 还得自己手动拉，比较麻烦

那如果我把他點開時，視窗的尺寸變大一點會對你有幫助嗎？  
現在是寫死寬 675px、高 415px，我可以改成螢幕寬高的 2/3。

**Comment by Hayakee** [comment]
啊，可以的，这样会舒服不少，不过我发现这个页面的框似乎是写死的，即使网页全屏也是，可能不用放大到2/3的程度。

还有一个很难受的点，就是输入框是不可调节的，长度超过输入框后的字会隐藏还得光标往后拉才能看到，原本的输入框还很短，没有类似github这样右下角有个钩子一样的东西可以调节高度。
![image](https://github.com/user-attachments/assets/acf36109-02ee-49ce-9956-df92f1b858e1)
最抽象的是顶部的标题部分写死了，甚至展示不全，Tenboro当时写这个也太随意了，我准备在论坛发个帖子问问他能不能优化一下😄。

**Comment by sk2589822** [comment]
我更新 1.14.0 了，會把 pop-up 的大小調整成視窗的 2/3。

在寫這個 script 的過程，看得出來 Tenboro 對前端不是這麼的熟悉，很多寫法不是那麼的好，就像你提到的問題就是其中一個。但剛好這個問題可以透過 CSS 來解決，這邊會建議你用可以覆蓋網站樣式的 extension，像是 [Stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)。

裝好後，打開 pop-up，點 pop-up tab 的這裡：

![image](https://github.com/user-attachments/assets/4609b0a7-29f8-4d8d-9de4-5453c5f3f386)

像這樣設定後（網址要調整一下，把 `.php` 後面的刪掉）：

![image](https://github.com/user-attachments/assets/780b7ea0-c3a1-4031-b35c-9b0d448bfccc)

就會變成這樣：

![image](https://github.com/user-attachments/assets/c67d8f0b-a6d6-4e32-bb01-ba0807485bd0)

```css
.stuffbox {
    width: 90% !important;
}

table {
    width: 100%;
}

td > input {
    width: -webkit-fill-available !important;
}
```

至於你提到的右下角的鉤子，會需要修改他的 HTML tag 才有辦法（將 `input` 改為 `textarea`），在不仔細追原始碼的情況下，我認為直接改會有點風險。

**Comment by sk2589822** [comment]
@Hayakee 忘了說，你的圖片是不是應該馬賽克一下？  
或直接拿掉也可以

**Comment by Hayakee** [comment]
啊，感谢提醒，已经删除图片了，我又发现一个使用中的问题，待会发issue。
