### ISSUE TITLE
[BUG] 归档下载已经解锁的点击取消无反应

### ISSUE THREAD

**Issue by Hayakee** [sk2589822/Exhentai-Enhancer#61]
![image](https://github.com/user-attachments/assets/c9b68ac7-4f90-4bf7-bacc-d4508e1f9c0e)
如图所示，因为IP切换导致出现IP quota，所以需要取消重新下载，但是点击cancel无反应，我把脚本关闭使用原始的正常取消。

**Comment by sk2589822** [comment]
感謝回報。

但最近比較忙一點，會再找時間修。

**Comment by sk2589822** [comment]
已於 1.13.0 中修正
