### ISSUE TITLE
Half of the functionality doesn't work.

### ISSUE THREAD

**Issue by maleon4ik** [sk2589822/Exhentai-Enhancer#62]
I apologize in advance, I don't know much about this topic. So, about a month ago the “Load All Gallery Images” function stopped working, I didn't care at first and thought it was a bug and the new update would fix it. Now I tried to use this feature again and it still doesn't work. Also, I tried other functions. Some work, some don't. I don't know, maybe I'm doing something wrong, or is it exhentai.org updated? I've tried installing previous versions of the script and changing browsers - doesn't help. In the script settings, the functions are enabled.
![image](https://github.com/user-attachments/assets/50444924-85fc-4509-a496-9ec1d6cd3ad9)

**Comment by sk2589822** [comment]
There are some DOM chages recently indeed.
I'll check "Load All Gallery Images" after I get off work.
For other functions, could you please point out which function is not working? Thanks

**Comment by sk2589822** [comment]
Should able to use "Load All Gallery Images" in `v1.15.2`.

**Comment by maleon4ik** [comment]
I apologize for the long wait for a response. It works. Thank you so much.

**Comment by maleon4ik** [comment]
About other functions I meant hotkeys, I apologize for the lack of clarification. Some work, some don't, for example the full screen key, switching 10 pages at once and zooming with ctrl+1-5 don't work.

**Comment by sk2589822** [comment]
Hi @maleon4ik,
Sorry for the late reply.

The functions you mentioned (e.g., full screen, navigating 10 pages at a time, etc.) are all working fine on my computer.

Are you using MPV (Multi-Page Viewer)?  
According to the documentation ([link](https://github.com/sk2589822/Exhentai-Enhancer?tab=readme-ov-file#multi-page-viewer-enhancer)), these functions only work under the following conditions:

1. The URL matches https://e(x)hentai.org/mpv/*/*.
2. Settings -> Multi-Page Viewer -> "Always use the Multi-Page Viewer?" is set to "Yup".

If these conditions are met, were you using English as your input method? Also, could you let me know the browser and its version you're using?

**Comment by maleon4ik** [comment]
Hello, @sk2589822,
I am sorry for the late responce too.

I think I figured out what's wrong. Isn't Multipage View a paid feature? If so, then yes, it is not available to me, I apologize.

**Comment by sk2589822** [comment]
> Isn't Multipage View a paid feature?

Partially, yes.  
But you can also earn points through other methods (such as HentaiVerse), but donating is the fastest way. In any case, you'll need to go to the Hath Perks page to redeem this feature.

![image](https://github.com/user-attachments/assets/367410ac-16fa-4a82-a957-7ea4791e9287)

[Here](https://e-hentai.org/mpv/530350/8b3c7e4a21/) is the demo page with MPV.

I'll close this issue since "Load All Gallery Images" has been fix in  `v1.15.2`.  
Thanks for the reporting!
