### ISSUE TITLE
[Bug] 关闭脚本中关于MPV全部选项时，MPV侧边缩略图消失

### ISSUE THREAD

**Issue by Hayakee** [sk2589822/Exhentai-Enhancer#63]
Exhentai-Enhancer设置如下：
![image](https://github.com/user-attachments/assets/e372b703-6d76-40b4-a858-c70fbc78e61e)
![image](https://github.com/user-attachments/assets/b72937e0-d23d-4e59-b7d6-eb3f6cdaef72)
我只启用了Better Popup，其他都是关闭的。
网站关于MPV的设置如下：
![image](https://github.com/user-attachments/assets/2f9d7434-142e-4ab0-b18e-7d4913344d01)
1.关闭Exhentai-Enhancer脚本时MPV界面：
<img src="https://github.com/user-attachments/assets/4ec87080-4c1f-42d7-bff0-419910abb2ef">
2.开启Exhentai-Enhancer脚本但是脚本设置如上只启用Better Popup时MPV界面：
<img src="https://github.com/user-attachments/assets/a3e524ba-56b2-40f0-bbc6-bbcb016fd157">
左侧的缩略图直接消失了，关闭脚本中有关MPV所有选项的表现应该和关闭Exhentai-Enhancer脚本一样，但并非如此。
我猜测是Exhentai-Enhancer脚本中有部分关于MPV的代码即使在脚本中把有关MPV设置的选项全部关闭依然会执行。

**Comment by Hayakee** [comment]
哈哈哈，开发者我们又见面了。
这次的问题是脚本里MPV的选项全关了还是会对MPV界面有影响，按情况脚本不应该再对MPV页面生效的。
因为我基本上只用脚本里的那个收藏、归档和种子窗口弹出（太好用了），这次使用MPV才发现这个bug。
我暂时的处理方式是在脚本的顶部加上

**Comment by Hayakee** [comment]
我更新到 1.15.3 了，设置和上面一样，其他的脚本和插件我都关闭了，但是还是一样，侧边会消失，看起来是隐藏了，不过元素还是在的，并且可以点击跳转。
![image](https://github.com/user-attachments/assets/8fa5a447-a9ad-46ca-965e-368068b3a9f5)

**Comment by sk2589822** [comment]
這次應該可以了，幫我試試 `1.15.4`

**Comment by Hayakee** [comment]
无敌辣，感谢开发者的高效率，已经修复，我关闭此issue。
